trigger:
  branches:
    include:
      - main   # or your default branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  app_location: "."            # Path to your HTML files
  api_location: ""             # Leave blank if you don't have an API
  output_location: ""          # Leave blank for plain HTML sites

steps:
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '$(app_location)'
      api_location: '$(api_location)'
      output_location: '$(output_location)'
      azure_static_web_apps_api_token: '$(deployment_token)'  # Set this in your pipeline variables (as a secret)
    env:
      azure_static_web_apps_api_token: $(deployment_token)
